### PR TITLE
fix: use union instead of OR

### PR DESCRIPTION
**Pull request by PietroPasotti**
Fixed breaking change, by adding back older python support.

### CODE REVIEW

**Comment by PietroPasotti** [comment]
Related: #228

**Comment by DanielArndt** [comment]
I think I'd prefer `from __future__ import annotations` if that works.

I'm not sure how far back in Python version support we are going, but 3.7+ should be enough?

**Comment by PietroPasotti** [comment]
IIRC we need 3.8+

**Comment by PietroPasotti** [comment]
IMHO given the rest of the library uses Union, this is the only place where we're introducing the new syntax, so perhaps, for the sake of consistency, it should remain like this until a major refactor?

**Review by saltiyazan — APPROVED** [review]

**Comment by saltiyazan** [comment]
> IMHO given the rest of the library uses Union, this is the only place where we're introducing the new syntax, so perhaps, for the sake of consistency, it should be fixed to use Union like I'm proposing until a major refactor?

I agree, we got a mix of those in V4. We probably need to make it consistent there too.

**Comment by DanielArndt** [comment]
It looks to me like the rest of the library actually uses `Optional`, not `Union`, so I think consistency would call for that instead. In any case, I think we should move to using the `|` in the future as that is preferred in Python 3.10+, and I'd rather move the syntax forward.

But this is super minor, just making a note for discussion's sake. I have no issues with this.

**Comment by PietroPasotti** [comment]
Ohhh my bad, I didn't even look at the other type, I saw an OR and went for Union. Sorry -_-

**Comment by DanielArndt** [comment]
No worries, you're still right that `| None` would have been [more] out of place :smile:

**Pull request merged**
